# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = AutoPilot
DESTDIR = ./x64/Debug
CONFIG += debug
INCLUDEPATH += F:\\opencv\\build\\include
LIBS += F:\\opencv\\build\\install\\x64\\vc15\\bin\\opencv_world440d.dll
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(AutoPilot.pri)
